[pytest]
testpaths = ui-tests/tests
pythonpath = ui-tests
addopts =
    -v
    --base-url https://www.saucedemo.com
    --browser chromium
    --screenshot only-on-failure
    --tracing retain-on-failure
    --output test-results
    --junitxml=reports/ui-junit.xml
    --html=reports/ui-report.html
    --self-contained-html
markers =
    smoke: tests críticos y rápidos
